// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/getting-started":{"path":"getting-started","id":"docs/getting-started","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/alert/index":{"id":"components/alert/index","path":"components/alert","parentId":"DocLayout"},"components/button/index":{"id":"components/button/index","path":"components/button","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "E:__Users__lenovo__Documents__fantasy-ui-react__node_modules__dumi__dist__client__pages__404" */'E:/Users/lenovo/Documents/fantasy-ui-react/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'E:/Users/lenovo/Documents/fantasy-ui-react/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'E:/Users/lenovo/Documents/fantasy-ui-react/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/getting-started': React.lazy(() => import(/* webpackChunkName: "docs__getting-started.md" */'E:/Users/lenovo/Documents/fantasy-ui-react/docs/getting-started.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'E:/Users/lenovo/Documents/fantasy-ui-react/docs/index.md')),
'components/alert/index': React.lazy(() => import(/* webpackChunkName: "alert__index.md" */'E:/Users/lenovo/Documents/fantasy-ui-react/src/alert/index.md')),
'components/button/index': React.lazy(() => import(/* webpackChunkName: "button__index.md" */'E:/Users/lenovo/Documents/fantasy-ui-react/src/button/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "E:__Users__lenovo__Documents__fantasy-ui-react__node_modules__dumi__dist__client__pages__Demo__index" */'E:/Users/lenovo/Documents/fantasy-ui-react/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
