// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { SiteContext } from 'E:/Users/lenovo/Documents/fantasy-ui-react/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(true);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // mark loading when route change, page component will set false when loaded
        setLoading(true);

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {"name":"@fantasy955/fantasy-ui-react","description":"A React UI Library.","version":"0.1.2","license":"ISC","repository":{"type":"git","url":"git@github.com:fantasy995/fantasy-ui-react.git"},"authors":{"name":"fantasy955","email":"1642063542@qq.com"}},
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      themeConfig: {"title":"Fantasy UI","footer":"Copyright © 2023 | Powered by <a href=\"https://d.umijs.org\" target=\"_blank\" rel=\"noreferrer\">dumi</a>","prefersColor":{"default":"light","switch":true}},
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
