// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from 'E:/Users/lenovo/Documents/fantasy-ui-react/node_modules/dumi/dist/client/theme-api/index.js';
